# Pull base image
FROM scratch

# Label this image as prod
LABEL prod prod

# Set exposed port
ARG PORT
EXPOSE $PORT

# Get the application executable
COPY bin/habitech /

# Set entrypoint to run the application
ENTRYPOINT ["/habitech"]
