# Pull base image
FROM mysql/mysql-server

# Label this image as bld
LABEL bld bld

# Install dependencies
RUN yum install -y tar

# Create a volume to point to the host directory where the tarred DB will be stored.
VOLUME /tar

# Set the root password to b0ss
ENV MYSQL_ROOT_PASSWORD b0ss

# Get the sql file and helper scripts
COPY sql/habitech.sql /tmp/
COPY init_db.sh /

ENTRYPOINT ["/init_db.sh"]
